package com.vubq.fashionstorewebsite.enums;

public enum EOrderStatus {
    READY_TO_PICK,
    PICKING,
    CANCEL,
    MONEY_COLLECT_PICKING,
    PICKED,
    STORING,
    TRANSPORTING,
    SORTING,
    DELIVERING,
    MONEY_COLLECT_DELIVERING,
    DELIVERED,
    DELIVERY_FAIL,
    WAITING_TO_RETURN,
    RETURN,
    RETURN_TRANSPORTING,
    RETURN_SORTING,
    RETURNING,
    RETURN_FAIL,
    RETURNED,
    EXCEPTION,
    DAMAGE,
    LOST
}
